.PHONY: cstyle all clean

CC=cc
CFLAGS=-Wall -pedantic -std=c99 -Wshadow -Wpointer-arith -Wcast-qual \
	-Wstrict-prototypes -Werror=implicit-function-declaration

%.o: %.c
	$(CC) $(CFLAGS) -c $<

cstyle:
	@echo "checking C style"
	@find . -type f -name '*.[ch]' | while read file; do \
		../cstyle.pl $$file; \
	done | grep ':'; \
	if [ $$? -eq 0 ]; then \
		exit 1; \
	fi
