name: Build

on:
  push:
    paths-ignore:
    - README.md
    - UNLICENSE
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
    - name: Install pre-requisites (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends gcc build-essential libc6-dev gcc-multilib
    - name: build
      run: make
